apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:39
              env:
                - name: RENOVATE_PLATFORM
                  value: gitea
                - name: RENOVATE_ENDPOINT
                  value: "http://forgejo.forgejo.svc.cluster.local:3000/api/v1/"
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: token
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secret
                      key: github-token
                - name: RENOVATE_REPOSITORIES
                  value: "Alvaro.rm.rdt/homelab-k8s"
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_GIT_URLS
                  value: '{"Alvaro.rm.rdt/homelab-k8s":"http://forgejo.forgejo.svc.cluster.local:3000/Alvaro.rm.rdt/homelab-k8s.git"}'
                - name: GIT_AUTHOR_NAME
                  value: "Renovate Bot"
                - name: GIT_AUTHOR_EMAIL
                  value: "renovate@homelab.local"
                - name: GIT_COMMITTER_NAME
                  value: "Renovate Bot"
                - name: GIT_COMMITTER_EMAIL
                  value: "renovate@homelab.local"
