apiVersion: ENC[AES256_GCM,data:yww=,iv:ui9prDNhtBkVAzbiqPYETFGPYkPRFCDtI+5wZqc5mzE=,tag:lsb2stXjtvt0sQ4polLswA==,type:str]
kind: ENC[AES256_GCM,data:mBXThzNc,iv:vPypRyGL72TatZX4WlmV9JGNO7koXAYbArswS3TSPto=,tag:JKKUqLg7Qth01J3o9Zn5dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yrKmRJh2nPi2EDwaXEJ6HZE=,iv:muzQvGYDl8YwtlC+XayDmAGfgW+OF7qZvIVLz4iWXs4=,tag:c7F+6GUMDg+896amV4QI+w==,type:str]
    namespace: ENC[AES256_GCM,data:9b+NM8O2iD5Z,iv:YHOrvI2BliWvuu8wSGDt90XM1/WqpAEIkRXfWKdxXjs=,tag:mHTuQujXh/F9NmDu9/6Eow==,type:str]
type: ENC[AES256_GCM,data:QNORV9JU,iv:RNHEv8mPNilWgemIRH7IBmoJ4lof+HAWOKaJU/ji5rU=,tag:r2iLqGoe68DTo0Yr+gq7+A==,type:str]
stringData:
    OPENWEBUI_API_KEY: ENC[AES256_GCM,data:DNX0MpcWcEc4j8ApeZaSJpmY0eTwcsyb2zgJDWPawx9c0i4=,iv:WcJDpceEcoNNS3OW5l5Z43SmWM/e3LkPSdsWtst+lmA=,tag:pRnz8Uvx9vLlq+s192dPqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1Jncit6QjcwelEyYjV4
            SWVGOEYvMmFXaFVvVFVFeFpXcGlNVDlEajE4CkFWVmN2anJrRk5uUFlnNnYybXBT
            d01FYkgwVmw5bUVhckkyKzJFOVA5Q0EKLS0tIFJvZWRtZm1JUTRGUkNCckppU2N0
            SDV4ZWRBSTZUNERWZ2p6TFNuOGdySVkKFqxeiMdhU1BM2LRj8mG7vmNkp0twA/Re
            9J578LPXfvZRZvIO7lXTA5BxiFl4eXfywsrGyArAiBows6yWRrLuZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T11:33:28Z"
    mac: ENC[AES256_GCM,data:04CcysNowsuToxsiLe/V1r0NksQ2RT/bV1fwxe+exT0i2IwbtOSEeO+540jzrr5aCO0o4Mzno423dMW0C2RbCP55rDttJLEdF9tZXEtHlJBbo6IEdQ8+uo8afpd5U5rPEPCbdzcLE/315fNNCSMEF9UqXbofWa8i65aE2vqI1f4=,iv:48GV70L3h8UWqJV8J7K5uGbXWKzlRqCKAU8LlDWlk3w=,tag:1M5196h1KZ4vaLVfEy7iPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
