apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-smb-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: vaultwarden-smb-pv
