apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:17-vectorchord0.3.0-pgvectors0.3.0
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: db-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: db-user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: db-name
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-db-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
