apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-smb-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: immich-smb-pv
    volumeAttributes:
      source: "//u648454.your-storagebox.de/backup/immich"
    nodeStageSecretRef:
      name: immich-smb-creds
      namespace: immich
