apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-smb-pvc
  namespace: actualbudget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: actualbudget-smb-pv
