apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-runner
  namespace: act-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner
  template:
    metadata:
      labels:
        app: act-runner
    spec:
      containers:
        - name: act-runner
          image: code.forgejo.org/forgejo/runner:13
          command: ["/bin/sh", "-c"]
          args:
            - |
              forgejo-runner daemon --config /data/config.yaml
          volumeMounts:
            - name: runner-data
              mountPath: /data
            - name: config
              mountPath: /data/config.yaml
              subPath: config.yaml
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: runner-data
          persistentVolumeClaim:
            claimName: act-runner-data
        - name: config
          configMap:
            name: act-runner-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
