apiVersion: ENC[AES256_GCM,data:qag=,iv:vU9eWLGZvEWnnSk/F5z/XGgPJVizb6bM/1d2OYygAUU=,tag:GzMt6LQFX9Zl36baK8uz9Q==,type:str]
kind: ENC[AES256_GCM,data:8UTNqLxa,iv:o7EOdj90UzEJcZ+SpRq74kwlCanr+WPeUC+4GuHBYsw=,tag:92wrk9N+/Jdy5m7qBiJ3mQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kZXMnybNYIEaYP3AqvI9Pv+Z,iv:/kYQyydga8Ro5t+o4fTNhQzKIRPRD7s/eNInb+6e568=,tag:rcbbbsx8qEzMICEt9OJu+A==,type:str]
    namespace: ENC[AES256_GCM,data:mglHy09RoodgWw==,iv:BiIIz/QUDf0vn4jdzz7/x1joZR/c0QQ5pYsI60QTz+U=,tag:S43q1JwJhUBww7yDLmNsbw==,type:str]
type: ENC[AES256_GCM,data:/C3xmcrJ,iv:RfVaqbCToUM+UOFciLFalZGBj5cJOGmzVDsv9hnZEks=,tag:bt5y0CN4p/Xuv75TySoknQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:flVm1vkttSeKcO5c1Rxd89LfEEm4ZEKKavGyjqX0ZYZ7wGsmGyGttQ==,iv:7jd96gYQ5BZUdC8T52PF3dMzk8BmSRbHcMIy3KR7WiM=,tag:yPfNrOOXOaaIjkaCQbGBeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUpPSVMvbk1jL2R6Nld1
            ZGd4eTBsQUowbERyUDBHN0JnQTh6VGVDclZ3Cmg2VmswT0kyOVF1cmFYV1NGZ1BN
            S2FMQkxYejdHaHNHcWxDalRLVzJNWXcKLS0tIGpHZmZaV0lNWGlZTm1RQU93ZW8w
            WFkxYURRZWpUZ0lJRTEyMGVZeWhtWTAK7BG6SXnVdS31rUIfVIQ/rXy4Q96NU4z4
            8M8r95ckVuPSxHAn9jFyO/O79nj+99h2YB7momVUKOm1XTx3d2kOSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T18:21:17Z"
    mac: ENC[AES256_GCM,data:P7vpwfnVkVDcqpgAXXJ9LPi+6NyDSJeKV1zaGf2tC88gJHwZHxFPebI3aXw+0EzoQsv9AjmbS5msx1or5aijyuhWuYwnsOmi2cF7RuPEniHtuoOkmyGb0Gj6RL+rt5r/dKO8dLOnAB1K2P2c+a6F56FJiru5smGvCCd2cl5OqWc=,iv:M0qEiFziZpvQuWpWG8giAIDU33q8EhzwA1VS69eTssM=,tag:CV3SPiHGyte3Yv4m17kkIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
