apiVersion: ENC[AES256_GCM,data:+Pg=,iv:2CQS63J89/tRtNKbFngwePEMFCJtCtVdHGD4KeDkpAs=,tag:fFyvEwLoqjeAQGfCRfWaFw==,type:str]
kind: ENC[AES256_GCM,data:b0vDm9hR,iv:YKQby4xAzbIid87oxC0NFXMbihZsVdCxVX19i16t+wU=,tag:BOwUHay5HTFqhWEStD6D3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xeynnpU4ivY/mwTvIDHonjaZ,iv:ffW5Gs3U+LDLjhAEq5P7EWEvesBqAP6rfomn5c4BdPw=,tag:1TFeBEbkiL2k7Z6An46T9g==,type:str]
    namespace: ENC[AES256_GCM,data:pfbWaMVQpRjj1w==,iv:ZOsKP8jrzI1NizCuVxj+5WSFywbh9ug1ZSc8JsPA8cw=,tag:ekDRUdd8RPaIO2IWnrpZvQ==,type:str]
type: ENC[AES256_GCM,data:f5oL92Tk,iv:uvq8akFo9I3ECP6JUcI2lQgrzL6aY4v+h6/RKs5m9BY=,tag:5JCbxy9rslTbDuQ69IECGA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:KtpbKvvx4aGjbTy6TRjfatxVU9Ntejj/iANQWyLy4Qs5bx9IOFDbpQ==,iv:Oes8JIkz2gpLk8GpaY6O8MrCNvw/NmO8C22r1jEZY7s=,tag:LFcmUpyqenel1prVGnl99g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObGlRUXZFb1huazYzRW1D
            YUI3WlZzelNTQ1FTaTk1NURPbmVwMGNGMm5rCjk1bG9KSGNRUjJVYWdHQmZOWDY5
            UlpTRXp6YmFndTllTm96Tml0bUdMU1EKLS0tIDRXenA0T1VjazRIWmNVRzhuWjFZ
            NTJ1U0drRWU2bnNNM0lTRHBPN244NXcKvYHJX4/uvsYVzaRV17OY6R7CU9scfaEX
            fGtUA1nzgIPICMTdYAjIi8PhIl85ymrgEe6Vgv9zOA7N3IJh1OQ9dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T17:31:26Z"
    mac: ENC[AES256_GCM,data:cbAZGCqL1i90qFT+vAY9M6/l1QvHB7wxAl4ByS0RG0INGQqkeOeQ4fIlHlsCzsKvElPIZnyZ2dH+8HyFlF6me4eadj1R1eaS7AjwctEDrr2plxB78109EOT0gkeEPouwhlUQP2AKutWJMW1IjBtXOBT8LmJZFTGismGI6rkIlak=,iv:bSS3Dhq0PtUWnSOJU75WQWwpOjc2AK871rpctAb4jkY=,tag:URvHP5vYId8FscutIYEtqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
