apiVersion: ENC[AES256_GCM,data:l7o=,iv:FrSKxAA+LJ0n5pu8sgpsY8ACXcZO52irnn3kXtzwyD0=,tag:XlPqrUqzu+xpVP59/ui1vw==,type:str]
kind: ENC[AES256_GCM,data:YJMxwlS7,iv:A4g1O/kVV9DIasvM4tJ0T6zkfWxBrFww5OXb2ZClxhc=,tag:Uz5LmwZo/0qN7VR8hEzE6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S7rCjTGy2Bpf8DJybFdhCjg=,iv:Erg7WbjglZj1eWLUcq2EU9hLOKwZk5ua0rOLK9cDBoA=,tag:noYZjqVOCZfqtremNXQN0A==,type:str]
    namespace: ENC[AES256_GCM,data:fwMQjo0TG8kburM=,iv:e+ZzPXGJW1pQwjLlqZSzS9hqU6lrt7FdYN/8Guhanwk=,tag:ixjGsFxgtz/lq+WC5n86Xg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:DU0mQ/YB3S5duOYxJaWsd+Y=,iv:ioVw/6HQ/MPDMXC0VIR6cIMDj87OKjUcLWNV8wNzHh0=,tag:Ek3LAOakyWqRJZ4ahA07mQ==,type:str]
type: ENC[AES256_GCM,data:B8vnO24J,iv:BZkER3EIKY6yiEOWZAos+jEjeionCsjS55GqE1phPNE=,tag:dxWUICVutEfWJfq8X09Ijg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMjBDekN3TlJyMkR1ZEc5
            cVhzWjV6d04xMWlJSWFDbUtYZzFDbzVmdjBRCmE3YzFMZlNraG9Ld2lUQ2psRFc1
            am5QZUxJanpYRGgrTkd3UGlEZWFGV0EKLS0tIHFtcTNMZmJha2c2MnB0SG9SZW9N
            dzhxODhFM3N6d0ZPZG5KL3VKbFFocnMKdhUrQoSGrdbmnkjmfK4VNnyogzjDeov2
            5HO8ayx4qjsv1Hf59swj+UqELfThUbU5e5DTI9aFhci4pzK4yLQzQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-24T21:23:13Z"
    mac: ENC[AES256_GCM,data:pmhpzKc9vmo//ipz/3EWsAqsEaMDZQqmy8gRTGPg37nv1YdlEceooQZIEF8N5tUQU2VwH46O+qaiLI8bd9xATrhzAvZn/HCdn7mfGKyc89mH6yaybMrhjz8HgWjpNnopK8Mrey8RwubDAvUy2wA4AgHfaRUkHrdvdd8OPTjZYDU=,iv:y6PanTtLvqrL9E+H/NsQXvpmPPfsrAK0hf1ciU3eLxM=,tag:tqU+Ml8TcIuYo0Eg0FutUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
