apiVersion: ENC[AES256_GCM,data:/84=,iv:k9iLMEhuL3NM5nWVoP+LaPdF9q5obVUUBKHNIEefsoQ=,tag:2gC8c7YSRPa8JPkrMG1Hug==,type:str]
kind: ENC[AES256_GCM,data:qvuEPW5Y,iv:jzF2qt/1OPDw4qKrifuHHTyyjzW1JbpVBidEQ8ABI2k=,tag:C2byI5Sh1tauqWfq8HwIgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dJai6hvHu0KWjcANVQ==,iv:8CCqxXvHB5VoN+YNwQsZlUIcHLRx8rRIaV8NvVEix70=,tag:5NzPthxCyKYoN/DclQBEvg==,type:str]
    namespace: ENC[AES256_GCM,data:VFkpoPmxQwwUPQ==,iv:ds2j2FalzZF39qXHy1WM553jhR8DxcyreDHZQGfLVlg=,tag:VbEn8XThJp/V7rfUL+HbRw==,type:str]
type: ENC[AES256_GCM,data:zrh8CyYr,iv:Tj2OWDOMaZAbSUHxp2cVpvgE/izqmHdcTpA5z93+xYs=,tag:S7GmcFaf64WYSTAbz1s2LQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:QGcRGb0=,iv:p9mf1UVHIsp0SrmJrg0bsEh33hNg8nEltAs0XrAafMM=,tag:mS3ygDDIIQPLaJT1CMoLYA==,type:str]
    admin-password: ENC[AES256_GCM,data:07JneqqaajwqVOBlUswmpFA05INTZ9GumzP1BPcd368=,iv:XCCgnogSOiKfySEwbuOu1MPid2xwTd1XJR/lBq75PNM=,tag:PQHWCWjD2gtX6o8EVTv3Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Zkd5eHlkQWxZZVZpSTdX
            a1k4d0FGcFYvNkpyQkU1UW5iTHRSWnd0TmpvCnNpenlBV3dMUEoxQlk1ZTI1YkRF
            ZmNwUHFGbWRvV0ZPeUgyaXg2SEo3a0EKLS0tIHQvcnVoK2FLdzJROS91akRXYlpZ
            T1E4UzU3TVREVENPOWhrT2VyY0N3cTQK2tdPYIZqZNOyemNdSjMu9ta/arbpyZkP
            ja4iifIhDqIbGjSMDDc6ixDAdUeH75KxZV7YAfg6JSu+0EYsNaPkJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T15:14:16Z"
    mac: ENC[AES256_GCM,data:wHglmtdGZJDuGJZURispxTVBlSXmtpiUonNdiq1NApnAxi6+x6ZxAMF08lUcH+eP0H+WdmMZ6FHmYepbcD9eMhMxRNUuTkcSgVWzo6kYLrsoEamoiCQGDU3eW0gkEELw5s3iSXaHCBKwQv7vQVnJUTLkKWGcIBPXQpT6JoVwjqs=,iv:s4Mg1UFx1maav61WvuQ9PVs6YVaKK6Ww6FuUR0+a8gA=,tag:CtlHIv1Bufz7JZ83Ixl2Lw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
