apiVersion: ENC[AES256_GCM,data:3cc=,iv:SINq6YUbHMwn5hnYGITE4qqqlUKQtLwisRki8r/Iz2U=,tag:lw9RJPAHLKE4r8yDCPlKpw==,type:str]
kind: ENC[AES256_GCM,data:g05s+tju,iv:MW9Z4J8x8rK5SYp599mQ3+Oe+Pgg9i3pfdF4CfgW+5g=,tag:HdalYcPSjievlYNPkjjnVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vvPeE5u3qvxthrOKepiPLg==,iv:pt8Ne0XuZLBtYpQs2JRX9dHIFRM+Qd88/wJPZg77Vnw=,tag:deY4dPZFUMbcL6zJENXrQg==,type:str]
    namespace: ENC[AES256_GCM,data:tte9Lv80,iv:XmVwieANQVmq/pUUlihrc4LfdCG/2hOvzxMK8cM4SHA=,tag:DDzS5mfVBXWpyO11V6JI/A==,type:str]
type: ENC[AES256_GCM,data:fE81t4lT,iv:tAH8BlM7xKBKtJs5hlLYscFUCEwoOYsChYcJc6SLeYs=,tag:xF8a26XNqUMWTnFce8flMg==,type:str]
stringData:
    db-user: ENC[AES256_GCM,data:4G3W0URs,iv:4rp36kzBl5jjAADN96RNd3xAs0n82aeOv4K83/7cQ6s=,tag:Cr8diGamERWGnlKgd0Rqdg==,type:str]
    db-password: ENC[AES256_GCM,data:4TslCQg9N/gcgJZix7zi5jFxZXyvAlHf/yD4vKDS5cY=,iv:RRNFR9rdUmlR5G1Yj2w1TcQjY78GnX2owbeFHN0Dfq8=,tag:IfvIDfumaNZSgQysFKtnQg==,type:str]
    db-name: ENC[AES256_GCM,data:5wG1dnKa,iv:ThbnzS7MbL/PU25e5GQjltynBkkAEo1Ab+cbCHYuGpo=,tag:yqmQIiYLd9GkPDL9L5B36Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbXF0T3BHQ213L2VyWExW
            R2NEbU93QjdpdmduSlRrODczTGlrdmJ2WFZVCkNJWlpLRGpkV1A5ZUxKZzVxSi9K
            VEFrdWdVNGk3QnQ4UldwM1QyK3Erc28KLS0tIFZ5V25HTG1NRGJUaVRoRW43SHNm
            Z2txZ3NXZi9uZXo0MWFXMi9IMUp2emcKqKHlOd/x79iHf4jihMLhlpAP269Hxn2j
            kGqAT/54Jn7tdumDKFPAchOCLOhCAWgtlH6Vrh4a0edosQi+wRDsGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T22:30:02Z"
    mac: ENC[AES256_GCM,data:WN4LM5MJl5GXaAsmCgbVLBSWoG9LnHsIrY2mC7xHbDGderg55QNOPCnitfYAAJ4/emCE0qnYBY8+GQddGw1FLpZ9lfdIbUwnmQ7Yg9NA+5gvJKNVKbMkYvx1D9dhSJYSuxXQCN58kAd0kYX+Hdu3aoCN7k+LjQETmrNj3MGTojw=,iv:+tINEXsN9B7+dn0s9JLcqGfJ8piPXJLD+x/lN83htQ4=,tag:iTaSMa/iabUNXUbLzVeIQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
