apiVersion: ENC[AES256_GCM,data:/4k=,iv:WMbs8I5+3/69uea3XO3+bIYYzMmLG9mO0br8/5YdSUk=,tag:7Te6FLx8DsPrpqbA3SuleQ==,type:str]
kind: ENC[AES256_GCM,data:K3qfPmTr,iv:nndhGIkSG1pTKrz1CiSWej2HPV1m2Q8u7KLp7DJDoko=,tag:Zz9i2o3XaV+6I6TA9e35Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CHWmgj7hb+OG23Mw9aj16w==,iv:EQ9RHZgfMskuYYeC6tpNvjhbZ6NlB07VPHRYhkzsTUs=,tag:jJ8W4hWIDhd+6ZyIpvmkww==,type:str]
    namespace: ENC[AES256_GCM,data:03xLksoW,iv:d8hiDR6/gBVLToc9PkWs+ubzjBhfEI5WjHhsR2MSGGM=,tag:c3+xjFyK3uJmRKNNpdgs8Q==,type:str]
type: ENC[AES256_GCM,data:bA8X1uBa,iv:ZMKzURo4R5WvSgBzrVzqi3im/AOe82ogDluhsIeiwfY=,tag:F87BznikScodjeatgUlLig==,type:str]
stringData:
    username: ENC[AES256_GCM,data:xrHVqycxSA==,iv:YKR3Dq4Fdqp/oGDoj8HtUXhlDeS4D8a5yEIKGW9WIR4=,tag:s2i7MU81oDHSuECVL8O/ZQ==,type:str]
    password: ENC[AES256_GCM,data:xP7Qx/CzYmfm2P9DrzvSKwYO9Q==,iv:DRh+SoyIOLKqfBmnFXDLlWBOWVFdEQNe/CjzCJKc91c=,tag:eHIBX233ev3L+69vtbzuYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkozakJSRm92bDd4WUZJ
            RFhsd2x0VFN4QjNYak5RdWV3WThMQkZjVGpRCkg0VzhydGY3Sk9INzRKeHh5R3J5
            S2FUaUE3NUh0WDZZTFd6K2p2ZXM2TXMKLS0tIHVkSlV3eThnRVBpSmlwakFPR3dR
            NXltb29OVWdmVlNpenBBaklsZWFtTUkKAlw9/A0hrgbEaH2W/TfnpFw6hg7uMjnT
            YTZK6YFC0WJbL4Uwiegh7pGLtTdUrtGV/YRZvzdGp4hIOqOJAoiv6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T22:01:19Z"
    mac: ENC[AES256_GCM,data:4x9YmVzwUDOQRIfaGWMm4AWRY41BVzQXRtYzCy1UaYpNP3O0FKrUWmtZijgqebaAeh6sp7AUv8QZxMyQgYCgBuwqqPcq/0HBUG4O5hLjF43hS+rWKzUeIdnKwzVQlBUGI3nZwDeQBCWDEX4DN3ShmiOAaG0cPfxGIO95u1XtXVI=,iv:lIulbHylluLrFyTTQV6rOqKx+fuCJDGxeW2mw2RicQ8=,tag:bR/KHaC9av7hpTIK7/LHGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
