apiVersion: ENC[AES256_GCM,data:yww=,iv:ui9prDNhtBkVAzbiqPYETFGPYkPRFCDtI+5wZqc5mzE=,tag:lsb2stXjtvt0sQ4polLswA==,type:str]
kind: ENC[AES256_GCM,data:mBXThzNc,iv:vPypRyGL72TatZX4WlmV9JGNO7koXAYbArswS3TSPto=,tag:JKKUqLg7Qth01J3o9Zn5dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yrKmRJh2nPi2EDwaXEJ6HZE=,iv:muzQvGYDl8YwtlC+XayDmAGfgW+OF7qZvIVLz4iWXs4=,tag:c7F+6GUMDg+896amV4QI+w==,type:str]
    namespace: ENC[AES256_GCM,data:9b+NM8O2iD5Z,iv:YHOrvI2BliWvuu8wSGDt90XM1/WqpAEIkRXfWKdxXjs=,tag:mHTuQujXh/F9NmDu9/6Eow==,type:str]
type: ENC[AES256_GCM,data:QNORV9JU,iv:RNHEv8mPNilWgemIRH7IBmoJ4lof+HAWOKaJU/ji5rU=,tag:r2iLqGoe68DTo0Yr+gq7+A==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:g4/YYqnZWGJsPc3yqIkL/zSFf0MxjA4pV3Q/15QbTPf+VHk=,iv:UOPQfUh+gOA9d92Mm4KWzOs6RO4KKph6bs0OlO8T+iE=,tag:sLI1+sM67OMfF7DE3omjhg==,type:str]
    OPENAI_API_BASE_URL: ENC[AES256_GCM,data:bLV7Z5xVR6zoZ36pFXRyYduRmuhaiZfi,iv:gvWqUjkdoMHOn4f2qY/UKDbZGoyBgFWLa0GFKcj5LJI=,tag:9IU/k2/rKCFjUo0AzTZXcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1Jncit6QjcwelEyYjV4
            SWVGOEYvMmFXaFVvVFVFeFpXcGlNVDlEajE4CkFWVmN2anJrRk5uUFlnNnYybXBT
            d01FYkgwVmw5bUVhckkyKzJFOVA5Q0EKLS0tIFJvZWRtZm1JUTRGUkNCckppU2N0
            SDV4ZWRBSTZUNERWZ2p6TFNuOGdySVkKFqxeiMdhU1BM2LRj8mG7vmNkp0twA/Re
            9J578LPXfvZRZvIO7lXTA5BxiFl4eXfywsrGyArAiBows6yWRrLuZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T11:49:08Z"
    mac: ENC[AES256_GCM,data:bJ0rOprqWKBxV3kYovtGriQP9Rc/XoHMdrErCKwvRGbWW6Fzbe8xbJ7FXqxH7T74lR0JGfWg0Pi5X8B2on23iPeIRaB/vYL0gWybkuGUnqykdBm/SUsGUHGFUODd7CoQrRlubuHLlzcY9XppgZOIoIZOSIiCkC6dxI60EDhTb/I=,iv:pvIZWQRUdU3p+j6e2hhDKjyPcP+UMn7QmkxpkzyZevQ=,tag:43iiiyn8Cfd9zVSuEALtkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
