apiVersion: ENC[AES256_GCM,data:fwc=,iv:xa95AX8lKzHecghrCh2s84TqYgtjSxvVrIpZ2+22Auw=,tag:40UPgjfrVkp1/bGQXZ3qCA==,type:str]
kind: ENC[AES256_GCM,data:JSArcoFa,iv:UU0dhq8W1mXUOOId/q5UImGFURl2WlxajTEzUNLx+90=,tag:IupuKVqyFSXZWkTgIH0kYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TIcm3FGw+dv43iMIdtGv2Q==,iv:mjWTO3vpWEzf2topj4Ug+2jR/nJsWGd1RLCFFlImZfM=,tag:Iylqu4qYDBCzp8ZZ0xa+5g==,type:str]
    namespace: ENC[AES256_GCM,data:aLXjxYkbP8A=,iv:9NyJA3KQNiaD5fxJmjpBPeqrS4ZAxV3CF3bWzbf9rXM=,tag:H3RrNFpUrta7LghboSaFwg==,type:str]
type: ENC[AES256_GCM,data:kNp/Oedy,iv:JHiPFx2jnQcq6KLtssj0MQ81v8yVbL2z1duRtHIuK8Y=,tag:f/sM3wz28kZQCHcm3NhXrA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:fIq1HFxvorzjsPYa586v6fvLK0+zupRMlTmhkxBfeEFjlB6dVOlnbA==,iv:guMUTm8jYle455jT47FJ4PnvBJ5ilm32vuMwm6BargE=,tag:i5HQE2Fc1amA10djr8MFxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbHp4VXl3ZnJkajREc1U1
            SjFySHB3K280d2hGYkNKUFAwQTRpeGxsYUFFClp5V2JjbDJRWk1TV1VYOXpCV3RN
            ZUY4ckdNamJhYUlHa0dKc1NFQWJ6QlEKLS0tIERmYkRRTDNpOUdYNEpyWnZzTmw2
            ZXdwcEViYU15dWRGSTg1UnFuQkRDOWsKMzwbW0TJJoIrqJj2wyZhzT1RwezxAwW4
            V5f+5GLuDplS3Ktx1/sHPzHIwxz9x7c7PKMTMZfLb47kcWhUaxj7BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T16:47:52Z"
    mac: ENC[AES256_GCM,data:6b65esVHAZ5/1pW1aSnb6GtiRZExcubP11miBBg8c0XGX8ziC64jPxTZKF6chO5B6vzQwsgtkHbXV6f2THNCH+a4Z0+2ttZThdaFAE8uWquBwrKaiD+pAwHnuVIW3+P9kIghXQ2vGZrDceRO4S+G/MKJkhLIdPZQhdtSBE62WDY=,iv:RDA+Fjj+RnyrIoo5khCXQIVNhTvVuY7odYhtM/NEZbk=,tag:nFphArWVYqyxdkXV9Rjp/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
