apiVersion: ENC[AES256_GCM,data:zU4=,iv:Dl4C9zApXzeR6aKWNBvRErr67/lC/IBHZKKsCSDhtrE=,tag:fSMnffbjx4/P46cWdpPgFg==,type:str]
kind: ENC[AES256_GCM,data:+rqlPKMu,iv:KkR6NwM52RefeFH1vYoKzXzPGqFOCaCBtEZxV5tYZ8I=,tag:8QKH8unu1+EPECSFeoQEDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i+ZPxMD2vZQSlOCP4b2TIw==,iv:H1aXaQGEo93CF8MoH6duQpDoqjjMRztgXObxR+vqOc4=,tag:ndujFnW9CYI/eULX3s017Q==,type:str]
    namespace: ENC[AES256_GCM,data:cXU06bEeUGM=,iv:cLTdFxbUQof6hXrjOgBXIcAyEIxg3XfhzMArHNeLsz4=,tag:chfSM6tLPE5F0wLVb1hGgw==,type:str]
type: ENC[AES256_GCM,data:N+LCrhs+,iv:aL2sguuaxjM72Y36Taa8VUi1Up4apsS9XpTWx4e6A7I=,tag:V+JfVUCC60iXfn+kKpapLg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:hVAgzes1Kf0dM9K6KqxPQ87iKvHxjplNx80S6OwJhIp5HAdEtD1blg==,iv:IWTzbPUWe7fq2q6K7v1gxoA+PCDFra5RxwSr/W9VKO4=,tag:kK2iTzN1yw6gcUF2ULXWQg==,type:str]
    github-token: ENC[AES256_GCM,data:P3r1rlQhxPAEukj8OR1rLeg+J3dpqUW4K6o4byfh8/A2Ntyr7kId0O1nlHi+DNy7tdAePDGWxgTRpmwc5Qqk/B8grr3oVjVs5vO/9sJoWuxGkku0i3u/00HfCfzW,iv:wsG7xWqQZONdxWa5fhm4V62JenD6Drtce0NxpQJZqMQ=,tag:Jjh/NxfiKDslWNuVddhnQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMGhVYTdRaUpXelBDNUFK
            VWNiaWtjN1FaQ1FyN0ZDamdZUU9Ycll0MUg4CndMTlU0R3NUdHdzakZMa015QUFP
            SStyMFVQWnhuTWtUeEJLNEd2MUI0bG8KLS0tIFViM1IxRGhwcXU2MHN2K3hxaEp1
            VFZ5bzdncldUUDJRdEIzaDNrbU1WNlUKzO1djDd+ZdHosFsemlgnvCOtByTlGMLF
            fWQAavvf+XZ8u6dNzY4Gpn95OV7zRDwWBa+62siX8fG/zNsfYcCANA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:04:48Z"
    mac: ENC[AES256_GCM,data:lEw146mmDYS1y/lG6XjWNFwytiY2m3eipccKDGqvAViK2TQWFfV+LdT6tfOX44bSGnxv+eBafBFHGoaugPwO/6CfzAto/q/wK2KIFx3ICC4CQey2KfwY8suInzQxdICwyigPBFL5KtpiT3OgkXF6E9ak0luacCVFr5n2GB8AXvs=,iv:OB40euLcniffawcL7PXjVE80a4yU2lG2IkOb01YvB6s=,tag:vyWQ2FMmGJ4aW4ppV37VCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
