apiVersion: ENC[AES256_GCM,data:pYI=,iv:7eXsffHf5IPT7McZ3E+feRXXBt9hzOr7vROzgUok0GM=,tag:pLE9JcBJuleOIoNW9Z1ILw==,type:str]
kind: ENC[AES256_GCM,data:vWfOXwSC,iv:IMJcmJ4xlisKhB21wS1Kkxydi8H7UarBXIgVVIQIayc=,tag:89uWY/uKhb8NjIbwVEVU4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HsfKSDb1/p/WqMEEuwJ4jA==,iv:twcXB54h7CEhjTlIiDTmUPlGoMs+To0ADQk2GV6naaY=,tag:91lM9Vk2SIV5N27FghQydw==,type:str]
    namespace: ENC[AES256_GCM,data:DAdSmA2euxE=,iv:1l2xL+0FpT3ZkQWOZ1EuMwnkzTJA5xHkG/GoQ9eGvjw=,tag:0C7zF9i9Yhk2d4QKDKvWgQ==,type:str]
type: ENC[AES256_GCM,data:F5WlkF30,iv:yyyy0XlRT8yJdF6p8hC0xYIsTw2kU56NiftAx5B6W5U=,tag:C64qarSzG1ehHPBKjp8msw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:r6pm6DGfMKHiqZsORgqU/4vvB+TVyHecLIoRHFjTTQ8rLLKCiO1ZsA==,iv:fexfL89JX14QOLmsDKvEbrFKyymkTMn3XoGpA2E1aZY=,tag:bq5ebzZEHl3F19aFZUhrhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc2QycjBQWjluN3dOTENY
            VU1OUG0vK1hiL3JxNE9iQnFLckc5SVBLTUEwCkRqbDBIcm1sdFQ3dElLbTUyaTFj
            QXgxMGVBK3o3S0I0ZmJyOXVzMnJ4cTQKLS0tIG1VWWgreDd0dnRCN2d0MEVZdHhh
            dDQrNUd0UVRPekpoWkdPQTZqRFNuMFUKSEWtSTjYrF6PVEvR/CYV3SS597/vPuMA
            FQ3t4FFCp3VJl5uSNkL6LlKUR41KM38esG2zJCmC/VrTj4G00Kawnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T16:32:20Z"
    mac: ENC[AES256_GCM,data:jDyI0d+sA4yJ0ITZloemf/ILcvA1totb5gBLrv9GQ9Tvw4WyL5epf0LIibdiSZMrpVQ+PTJ7cC5i1icVGwyEW4r8MYsG5e3azChrmCkdrzy3SeqxWVJQBIIR9eOArUPa0ymWKeA8c4hJ6dmnk/VpCCu07APMjqClzTmn0bGSqBc=,iv:8ENntuLWZ3lq+ZiruSnT/MVaU6zIILOvhrfe2AGG2TA=,tag:kqab97AbFdAyyxZtezNp3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
