apiVersion: ENC[AES256_GCM,data:kwA=,iv:FXptEGsQITuV/SeKmnceQkOYM81gQs403BtDcpAn/W8=,tag:CQJlCSiZrggIVk9wfimhAA==,type:str]
kind: ENC[AES256_GCM,data:GRHNBcBy,iv:0xhyHdSX4RwiYrkhjGVU2a0cjrvQJ8xNAAn20UDRakI=,tag:tAwMMTCt4Tll+7GSfgggPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cwqNL3PhEoD6FUFvJYPO9yQ8IQ==,iv:WgNPARRCwcAPz2QYgehWeYBOfMGDKZQrpc/i6ma9quE=,tag:TS2jYQ/tONUR4uHVhJtL9g==,type:str]
    namespace: ENC[AES256_GCM,data:kZ0TZtfuJhKH+Pk=,iv:SSFn47/SoE1HnDZw8xMKD3YWeop/C+8PaV/m7+hsLrw=,tag:XiUKHbA8k4IwwuDHWCp+oA==,type:str]
type: ENC[AES256_GCM,data:wBiDvgdM,iv:nppBu3ibiaQbePa8P2xEKIgY+aCUp6+JXiPCts29R9Q=,tag:r9bExoIBU/9oPFu9e2ebUw==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:Wn1UCfeXQpcsmcBlkrjXDM/szQj7fkG8KwfyGbUT9SNNrrW4krWRrf0SCO2n3ZBf/xjyANDLgsm8jbCviTBxwQ==,iv:a0Yz2YGuAFOe01H9/kyv+vqNUrRyWnfj2/3zLeasOww=,tag:u19TXqOF0PjPRaCRCW9Ktg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3frpm5mxkcygywz5t6cnuz8cw5j2s9f69xvaum68m3s24r9cquspryzmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTWZ3aW9sdVoySG1xZk9R
            clZ0S1I3WFU4RGdxWFZHRWdwUlZNVnl1NGtRCnZGY1VkMzlMQUlhL3N4b0t1TEps
            c21rUU5ZQkRLZVhDNXUyQjcrbk1ycGcKLS0tIDdVR012cnV1OGx2eE5IV0xyMmNI
            dFFLVk1leG5CNXg5cVZDakJQbjFTdEkK/5G11N2OnmvY6VinlomlefrJG3ApY2IQ
            s8r0uz2wK83d2bh3Q6JHo+0UrarfFeeONEwd5Z1YOrElkNRsAQU4TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:50:11Z"
    mac: ENC[AES256_GCM,data:E67wO5IHUNPQWTbN6OUNuly0ep1NeRCMGpksXhfCLPVOAAaH+R5Nfb8yJeBquVXkU24nVlMgAM8+RjmcLf0yB+Kj6iMbUTV4zPEKMXCBjPAtCmA6V06gJQZEQz1rswiHTvjqPa4Um9at0WvQAhyZMUzxL2+VA0BGJqVE8Fu7BV4=,iv:fjudUz9eVIw7WhckiHIKmvbaH2PeKHnmKZ/B/Qenf+4=,tag:vW/vVJhEllqzUKM2A/x49A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
